In [19]:
import numpy as np
import pandas as pd
import mlrose_hiive as mlrh
import mlrose 
import matplotlib.pyplot as plt
my_random_state = 318
import time
import random

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler, OneHotEncoder, LabelEncoder
from sklearn.metrics import accuracy_score,plot_confusion_matrix
# from sklearn.datasets import load_iris
algorithms = ['GD','RHC', 'SA', 'GA']


In [20]:
##### Adult Income
### http://archive.ics.uci.edu/ml/datasets/Adult
data = pd.read_csv('datafiles/adult.csv')
data

y_data_raw = data.income

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit(y_data_raw.values.tolist())
y_data = le.transform(y_data_raw)


x_data_raw = data.loc[:,'age':'native-country']

from sklearn.preprocessing import OrdinalEncoder
enc = OrdinalEncoder()
enc.fit(x_data_raw.values.tolist())
x_data = enc.transform(x_data_raw)

# temp = enc.inverse_transform(x_data)


x_train, x_test, y_train, y_test = train_test_split(x_data, y_data, train_size=0.7, random_state=my_random_state, shuffle=True)
print(x_train.shape, x_test.shape, y_train.shape, y_test.shape)

(22792, 14) (9769, 14) (22792,) (9769,)


In [21]:
train_accuracies = np.zeros(4)
test_accuracies = np.zeros(4)
optim_time = np.zeros(4)
train_time = np.zeros(4)
test_time = np.zeros(4)

# 1. gradient_descent

In [ ]:
# Initialize neural network object and fit object
tic = time.perf_counter() 
nn = mlrose.NeuralNetwork(hidden_nodes = [20,20,20], # activation = 'relu', 
                                 algorithm = 'gradient_descent', # max_iters = 1000, 
                                 learning_rate = 0.001, # bias = True, is_classifier = True, 
                                 early_stopping = True, clip_max = 5, max_attempts = 100, 
                                 random_state = my_random_state, curve = True)
toc = time.perf_counter() 
optim_time[0] = toc-tic
print(f"optimization time {toc - tic} seconds")
print()


tic = time.perf_counter() 
nn.fit(x_train, y_train)
toc = time.perf_counter() 
train_time[0] = toc-tic
print(f"training time {toc - tic} seconds")
print()

print("Value of loss function for fitted weights when fit is performed\n",nn.loss)
# print("fitted_weights", nn_gd.fitted_weights)
# nn.fitted_weights
nn.fitted_weights.shape
# learning_rate = 0.1
# Value of loss function for fitted weights when fit is performed 1.3862943611198906
# array([-5.        , -0.31964703, -5.        , ...,  5.        ,
#        -5.        , -0.11450284])

# learning_rate = 0.001
# Value of loss function for fitted weights when fit is performed 0.25105686815160916
# array([ 0.09052286, -0.31964703, -0.67567475, ...,  1.29516855,
#         0.22538836,  0.15522131])

In [ ]:
# Predict labels for train set and assess accuracy
y_train_pred = nn.predict(x_train)
y_train_accuracy = accuracy_score(y_train, y_train_pred)
print(y_train_accuracy)
train_accuracies[0] = y_train_accuracy
# 0.9319148936170213 @ learning_rate = 0.001
# 0.4 @ learning rate = 0.1


# Predict labels for test set and assess accuracy

tic = time.perf_counter() 
y_test_pred = nn.predict(x_test)
toc = time.perf_counter() 
test_time[0] = toc-tic
print(f"testing time {toc - tic} seconds")

y_test_accuracy = accuracy_score(y_test, y_test_pred)
print(y_test_accuracy)
test_accuracies[0] = y_test_accuracy
# 0.9306930693069307 @ learning_rate = 0.001
# 0.48514851485148514 @ learning_rate = 0.1

# nn_gd.predicted_probs


# plot_confusion_matrix(nn, x_test, y_test,normalize='true',cmap=plt.cm.Blues)
# plt.savefig('NN/NN_GD_confusion_matrix_normalized.png') 
# plt.show()

nn_gd = nn ## save

# 2. random_hill_climb

In [ ]:
tic = time.perf_counter() 
nn = mlrose.NeuralNetwork(hidden_nodes = [20,20,20], # activation = 'relu', 
                                 algorithm = 'random_hill_climb', max_iters = 5000, 
                                 restarts = 3, #learning_rate = 0.001, # bias = True, is_classifier = True, 
                                 early_stopping = True, clip_max = 5, max_attempts = 100, 
                                 random_state = my_random_state, curve = True)
toc = time.perf_counter() 
optim_time[1] = toc-tic
print(f"optimization time {toc - tic} seconds")
print()


tic = time.perf_counter() 
nn.fit(x_train, y_train)
toc = time.perf_counter() 
train_time[1] = toc-tic
print(f"training time {toc - tic} seconds")
print()

print("Value of loss function for fitted weights when fit is performed\n",nn.loss)
# print("fitted_weights", nn_gd.fitted_weights)
# nn.fitted_weights
nn.fitted_weights.shape

In [ ]:
# Predict labels for train set and assess accuracy
y_train_pred = nn.predict(x_train)
y_train_accuracy = accuracy_score(y_train, y_train_pred)
print(y_train_accuracy)
train_accuracies[1] = y_train_accuracy

# Predict labels for test set and assess accuracy

tic = time.perf_counter() 
y_test_pred = nn.predict(x_test)
toc = time.perf_counter() 
test_time[1] = toc-tic
print(f"testing time {toc - tic} seconds")

y_test_accuracy = accuracy_score(y_test, y_test_pred)
print(y_test_accuracy)
test_accuracies[1] = y_test_accuracy

# nn_gd.predicted_probs


nn_rhc = nn ## save

In [ ]:
train_accuracies,test_accuracies, optim_time, train_time, test_time

# simulated_annealing

In [ ]:
tic = time.perf_counter() 
nn = mlrose.NeuralNetwork(hidden_nodes = [20,20,20], # activation = 'relu', 
                                 algorithm = 'simulated_annealing', max_iters = 10000, 
                                 #learning_rate = 0.001, # bias = True, is_classifier = True, 
                                 early_stopping = True, clip_max = 5, max_attempts = 100, 
                                 random_state = my_random_state, curve = True)
toc = time.perf_counter() 
optim_time[2] = toc-tic
print(f"optimization time {toc - tic} seconds")
print()


tic = time.perf_counter() 
nn.fit(x_train, y_train)
toc = time.perf_counter() 
train_time[2] = toc-tic
print(f"training time {toc - tic} seconds")
print()

print("Value of loss function for fitted weights when fit is performed\n",nn.loss)
# print("fitted_weights", nn_gd.fitted_weights)
# nn.fitted_weights
nn.fitted_weights.shape

In [ ]:
# Predict labels for train set and assess accuracy
y_train_pred = nn.predict(x_train)
y_train_accuracy = accuracy_score(y_train, y_train_pred)
print(y_train_accuracy)
train_accuracies[2] = y_train_accuracy

# Predict labels for test set and assess accuracy

tic = time.perf_counter() 
y_test_pred = nn.predict(x_test)
toc = time.perf_counter() 
test_time[2] = toc-tic
print(f"testing time {toc - tic} seconds")

y_test_accuracy = accuracy_score(y_test, y_test_pred)
print(y_test_accuracy)
test_accuracies[2] = y_test_accuracy

# nn_gd.predicted_probs


nn_sa = nn ## save

In [ ]:
train_accuracies,test_accuracies, optim_time, train_time, test_time
# (array([0.93191489, 0.95744681, 0.88510638, 0.        ]),
#  array([0.93069307, 0.92079208, 0.91089109, 0.        ]),
#  array([7.36000002e-05, 7.58999995e-05, 8.43999997e-05, 0.00000000e+00]),
#  array([ 0.3091845, 26.5170176,  9.956555 ,  0.       ]),
#  array([0.000536 , 0.0003569, 0.0004006, 0.       ]))

# genetic_alg

In [ ]:
tic = time.perf_counter() 
nn = mlrose.NeuralNetwork(hidden_nodes = [20,20,20], # activation = 'relu', 
                                 algorithm = 'genetic_alg', max_iters = 1000, 
                                 #learning_rate = 0.001, # bias = True, is_classifier = True, 
                                 early_stopping = True, clip_max = 5, max_attempts = 100, 
                                 random_state = my_random_state, curve = True)
toc = time.perf_counter() 
optim_time[3] = toc-tic
print(f"optimization time {toc - tic} seconds")
print()


tic = time.perf_counter() 
nn.fit(x_train, y_train)
toc = time.perf_counter() 
train_time[3] = toc-tic
print(f"training time {toc - tic} seconds")
print()

print("Value of loss function for fitted weights when fit is performed\n",nn.loss)
# print("fitted_weights", nn_gd.fitted_weights)
# nn.fitted_weights
nn.fitted_weights.shape

In [ ]:
# Predict labels for train set and assess accuracy
y_train_pred = nn.predict(x_train)
y_train_accuracy = accuracy_score(y_train, y_train_pred)
print(y_train_accuracy)
train_accuracies[3] = y_train_accuracy

# Predict labels for test set and assess accuracy

tic = time.perf_counter() 
y_test_pred = nn.predict(x_test)
toc = time.perf_counter() 
test_time[3] = toc-tic
print(f"testing time {toc - tic} seconds")

y_test_accuracy = accuracy_score(y_test, y_test_pred)
print(y_test_accuracy)
test_accuracies[3] = y_test_accuracy

# nn_gd.predicted_probs


nn_ga = nn ## save

In [ ]:
train_accuracies,test_accuracies, optim_time, train_time, test_time

# Accuracy & Time

In [ ]:
#### https://matplotlib.org/3.1.1/gallery/lines_bars_and_markers/barchart.html

width = 0.4  # the width of the bars
x = np.arange(len(algorithms))

fig, ax = plt.subplots()
rects1 = ax.bar(x - width/2, train_accuracies, width, label='train')
rects2 = ax.bar(x + width/2, test_accuracies, width, label='test')

plt.gca().set_ylim(0.6, 1.0)

# Add some text for labels, title and custom x-axis tick labels, etc.
ax.set_ylabel('Prediction Accuracy')
ax.set_title('prediction accuracy on training/testing set')
ax.set_xticks(x)
ax.set_xticklabels(['GD','RHC','SA','GA'])
ax.legend()

def autolabel(rects):
    """Attach a text label above each bar in *rects*, displaying its height."""
    for rect in rects:
        height = rect.get_height()
        ax.annotate('{:0.2f}%'.format(height*100),
                    xy=(rect.get_x() + rect.get_width() / 2, height),
                    xytext=(0, 3),  # 3 points vertical offset
                    textcoords="offset points",
                    ha='center', va='bottom')


autolabel(rects1)
autolabel(rects2)

fig.tight_layout()
plt.savefig('NN/accuracy.png') 

plt.show()

In [ ]:
fig = plt.figure()
ax = fig.add_axes([0,0,1,1])

rects = ax.bar(['GD','RHC','SA','GA'],train_time)


def autolabel2(rects):
    """Attach a text label above each bar in *rects*, displaying its height."""
    for rect in rects:
        height = rect.get_height()
        ax.annotate('{:0.4f}'.format(height),
                    xy=(rect.get_x() + rect.get_width()/2, height),
                    xytext=(0, 3),  # 3 points vertical offset
                    textcoords="offset points",
                    ha='center', va='bottom')
autolabel2(rects)

# plt.ylim(.1, 2000)
plt.title('Training time (logscale)')
ax.set_yscale('log')
# plt.xlabel('classifiers')
plt.ylabel("training time [second]")
plt.savefig('NN/training_time.png') 
plt.show()


# fitness curve

In [22]:
numiters = [100,500,1000,2000,5000,10000]
train_accu_fit = np.zeros((4,6))
train_time_fit = np.zeros((4,6))
test_accu_fit = np.zeros((4,6))
algorithms = ['gradient_descent','random_hill_climb','simulated_annealing','genetic_alg']

In [23]:
# gradient_descent
for i in range(len(numiters)):
    it = numiters[i]
    nn = mlrose.NeuralNetwork(hidden_nodes = [90,90,90,90], # activation = 'relu', 
                                 algorithm = 'gradient_descent', max_iters = it, 
                                 learning_rate = 0.0001, # bias = True, is_classifier = True, 
                                 early_stopping = True, clip_max = 5, max_attempts = 100, 
                                 random_state = my_random_state, curve = True)
    
    tic = time.perf_counter() 
    nn.fit(x_train, y_train)
    toc = time.perf_counter() 
    train_time_fit[0][i] = toc - tic
    print(f"training time {toc - tic} seconds")
    
    y_train_pred = nn.predict(x_train)
    y_train_accuracy = accuracy_score(y_train, y_train_pred)
    print(y_train_accuracy)
    train_accu_fit[0][i] = y_train_accuracy
    
    y_test_pred = nn.predict(x_test)
    y_test_accuracy = accuracy_score(y_test, y_test_pred)
    print(y_test_accuracy)
    test_accu_fit[0][i] = y_test_accuracy

training time 44.269546399999854 seconds
0.7609248859248859
0.7551438222950149
training time 40.7635408000001 seconds
0.7609248859248859
0.7551438222950149
training time 39.69460509999999 seconds
0.7609248859248859
0.7551438222950149
training time 39.30813360000002 seconds
0.7609248859248859
0.7551438222950149
training time 39.93011000000024 seconds
0.7609248859248859
0.7551438222950149
training time 39.823226100000284 seconds
0.7609248859248859
0.7551438222950149


In [24]:
# RHC
for i in range(len(numiters)):
    it = numiters[i]
    nn = mlrose.NeuralNetwork(hidden_nodes = [90,90,90,90], # activation = 'relu', 
                                 algorithm = algorithms[1], max_iters = it, 
                                 restarts = 3,#learning_rate = 0.001, # bias = True, is_classifier = True, 
                                 early_stopping = True, clip_max = 5, max_attempts = 100, 
                                 random_state = my_random_state, curve = True)
    
    tic = time.perf_counter() 
    nn.fit(x_train, y_train)
    toc = time.perf_counter() 
    train_time_fit[1][i] = toc - tic
    print(f"training time {toc - tic} seconds")
    
    y_train_pred = nn.predict(x_train)
    y_train_accuracy = accuracy_score(y_train, y_train_pred)
    print(y_train_accuracy)
    train_accu_fit[1][i] = y_train_accuracy
    
    y_test_pred = nn.predict(x_test)
    y_test_accuracy = accuracy_score(y_test, y_test_pred)
    print(y_test_accuracy)
    test_accu_fit[1][i] = y_test_accuracy

training time 61.89317280000023 seconds
0.31221481221481223
0.3170232367693725
training time 305.75816529999975 seconds
0.7918567918567918
0.7886170539461562
training time 598.2730277999999 seconds
0.7926026676026676
0.7886170539461562
training time 1021.1213736999998 seconds
0.7926465426465427
0.7893336063056607


KeyboardInterrupt: 

In [31]:
# SA
for i in range(4,len(numiters)):
    it = numiters[i]
    print(i)
    print(it)
    nn = mlrose.NeuralNetwork(hidden_nodes = [90,90,90,90], # activation = 'relu', 
                                 algorithm = algorithms[2], max_iters = it, 
                                 #learning_rate = 0.001, # bias = True, is_classifier = True, 
                                 early_stopping = True, clip_max = 5, max_attempts = 100, 
                                 random_state = my_random_state, curve = True)
    
    tic = time.perf_counter() 
    nn.fit(x_train, y_train)
    toc = time.perf_counter() 
    train_time_fit[2][i] = toc - tic
    print(f"training time {toc - tic} seconds")
    
    y_train_pred = nn.predict(x_train)
    y_train_accuracy = accuracy_score(y_train, y_train_pred)
    print(y_train_accuracy)
    train_accu_fit[2][i] = y_train_accuracy
    
    y_test_pred = nn.predict(x_test)
    y_test_accuracy = accuracy_score(y_test, y_test_pred)
    print(y_test_accuracy)
    test_accu_fit[2][i] = y_test_accuracy

4
5000
training time 1219.3594465999995 seconds
0.7947525447525448
0.7888217831917289
5
10000


KeyboardInterrupt: 

In [29]:
# GA
for i in range(len(numiters)):
    it = numiters[i]
    nn = mlrose.NeuralNetwork(hidden_nodes = [90,90,90,90], # activation = 'relu', 
                                 algorithm = algorithms[3], max_iters = it, 
                                 #learning_rate = 0.001, # bias = True, is_classifier = True, 
                                 early_stopping = True, clip_max = 5, max_attempts = 100, 
                                 random_state = my_random_state, curve = True)
    
    tic = time.perf_counter() 
    nn.fit(x_train, y_train)
    toc = time.perf_counter() 
    train_time_fit[3][i] = toc - tic
    print(f"training time {toc - tic} seconds")
    
    y_train_pred = nn.predict(x_train)
    y_train_accuracy = accuracy_score(y_train, y_train_pred)
    print(y_train_accuracy)
    train_accu_fit[3][i] = y_train_accuracy
    
    y_test_pred = nn.predict(x_test)
    y_test_accuracy = accuracy_score(y_test, y_test_pred)
    print(y_test_accuracy)
    test_accu_fit[3][i] = y_test_accuracy

KeyboardInterrupt: 

In [28]:
    

train_accu_fit,train_time_fit,test_accu_fit

(array([[0.76092489, 0.76092489, 0.76092489, 0.76092489, 0.76092489,
         0.76092489],
        [0.31221481, 0.79185679, 0.79260267, 0.79264654, 0.        ,
         0.        ],
        [0.24271674, 0.29308529, 0.78900491, 0.78939979, 0.        ,
         0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        ]]),
 array([[  44.2695464,   40.7635408,   39.6946051,   39.3081336,
           39.93011  ,   39.8232261],
        [  61.8931728,  305.7581653,  598.2730278, 1021.1213737,
            0.       ,    0.       ],
        [  27.2996384,  132.2044536,  256.1663907,  512.7198243,
            0.       ,    0.       ],
        [   0.       ,    0.       ,    0.       ,    0.       ,
            0.       ,    0.       ]]),
 array([[0.75514382, 0.75514382, 0.75514382, 0.75514382, 0.75514382,
         0.75514382],
        [0.31702324, 0.78861705, 0.78861705, 0.78933361, 0.        ,
         0.        ],
        [0.2485413 , 0.29675504, 0.786

In [ ]:
### test accuracy
plt.figure()
plt.semilogx(numiters, test_accu_fit[0], label = 'GD')
plt.semilogx(numiters, test_accu_fit[1], label = 'RHC')
plt.semilogx(numiters, test_accu_fit[2], label = 'SA')
plt.semilogx(numiters[0:2], test_accu_fit[3][0:2], label = 'GA')


plt.title('Fitness curve for NN - test accuracy')
plt.xlabel('max_iter')
plt.ylabel("accuracy")
plt.legend(loc="best")
plt.grid()
plt.savefig('NN/fitness_testaccuracy.png')
plt.show()

In [ ]:
numiters[0:2]

In [ ]:
### train accuracy
plt.figure()
plt.semilogx(numiters, train_accu_fit[0], label = 'GD')
plt.semilogx(numiters, train_accu_fit[1], label = 'RHC')
plt.semilogx(numiters, train_accu_fit[2], label = 'SA')
plt.semilogx(numiters[0:2], train_accu_fit[3][0:2], label = 'GA')


plt.title('Fitness curve for NN - train accuracy')
plt.xlabel('max_iter')
plt.ylabel("accuracy")
plt.legend(loc="best")
plt.grid()
plt.savefig('NN/fitness_trainaccuracy.png')
plt.show()

In [ ]:
### train time
plt.figure()
plt.semilogx(numiters, train_time_fit[0], label = 'GD')
plt.semilogx(numiters, train_time_fit[1], label = 'RHC')
plt.semilogx(numiters, train_time_fit[2], label = 'SA')
plt.semilogx(numiters[0:2], train_time_fit[3][0:2], label = 'GA')


plt.title('Fitness curve for NN - training time (log-log scale)')
plt.xlabel('max_iter')
plt.yscale("log")
plt.ylabel("time [second]")
plt.legend(loc="best")
plt.grid()
plt.savefig('NN/fitness_traintime.png')
plt.show()